import { existsSync, mkdirSync, rmSync, writeFileSync } from "node:fs";
import { homedir } from "node:os";
import { dirname, join } from "node:path";
import { spawnSync } from "node:child_process";
import { daemonLogPath } from "../lib/paths.js";

export const SYSTEMD_SERVICE_NAME = "hasna-dispatch-daemon.service";

export type ServiceAction = "install" | "start" | "stop" | "restart" | "status" | "uninstall";

export interface ServiceResult {
  ok: boolean;
  action: ServiceAction;
  detail: string;
  unitPath?: string;
  stdout?: string;
  stderr?: string;
}

export interface SystemdUnitOptions {
  execPath: string;
  cliEntry: string;
  serviceName?: string;
  dataDir?: string;
}

function configHome(): string {
  return process.env.XDG_CONFIG_HOME || join(homedir(), ".config");
}

export function systemdUserUnitPath(serviceName: string = SYSTEMD_SERVICE_NAME): string {
  return join(configHome(), "systemd", "user", serviceName);
}

function unitQuote(value: string): string {
  if (/^[A-Za-z0-9_@%+=:,./-]+$/.test(value)) return value;
  return `"${value.replace(/["\\]/g, "\\$&")}"`;
}

export function buildSystemdUserUnit(opts: SystemdUnitOptions): string {
  const name = opts.serviceName ?? SYSTEMD_SERVICE_NAME;
  const execStart = [opts.execPath, opts.cliEntry, "daemon", "run"].map(unitQuote).join(" ");
  const lines = [
    "[Unit]",
    "Description=Hasna dispatch scheduled prompt daemon",
    "Documentation=https://github.com/hasna/dispatch",
    "",
    "[Service]",
    "Type=simple",
  ];
  if (opts.dataDir) lines.push(`Environment=DISPATCH_DATA_DIR=${unitQuote(opts.dataDir)}`);
  lines.push(
    `ExecStart=${execStart}`,
    "Restart=on-failure",
    "RestartSec=10s",
    `StandardOutput=append:${daemonLogPath()}`,
    `StandardError=append:${daemonLogPath()}`,
    "",
    "[Install]",
    "WantedBy=default.target",
    "",
    `# Generated by @hasna/dispatch for ${name}`,
  );
  return lines.join("\n");
}

function runSystemctl(args: string[]): ServiceResult {
  const action = (args[0] ?? "status") as ServiceAction;
  if (process.platform !== "linux") {
    return {
      ok: false,
      action,
      detail: "user-level systemd service management is only supported on Linux; use dispatch daemon ensure/start on this platform",
    };
  }
  const systemctl = spawnSync("systemctl", ["--user", ...args, SYSTEMD_SERVICE_NAME], {
    encoding: "utf8",
    stdio: ["ignore", "pipe", "pipe"],
  });
  return {
    ok: systemctl.status === 0,
    action,
    detail: systemctl.status === 0 ? `systemctl --user ${args.join(" ")} ${SYSTEMD_SERVICE_NAME}` : "systemctl --user failed",
    stdout: systemctl.stdout ?? "",
    stderr: systemctl.stderr ?? "",
  };
}

export function serviceAction(
  action: ServiceAction,
  opts: { execPath?: string; cliEntry?: string; startAfterInstall?: boolean } = {},
): ServiceResult {
  const unitPath = systemdUserUnitPath();
  if (action === "install") {
    if (process.platform !== "linux") {
      return {
        ok: false,
        action,
        detail: "user-level systemd service installation is only supported on Linux",
        unitPath,
      };
    }
    if (!opts.execPath || !opts.cliEntry) {
      return { ok: false, action, detail: "cannot determine CLI entry for service unit", unitPath };
    }
    mkdirSync(dirname(unitPath), { recursive: true });
    mkdirSync(dirname(daemonLogPath()), { recursive: true });
    writeFileSync(
      unitPath,
      buildSystemdUserUnit({ execPath: opts.execPath, cliEntry: opts.cliEntry, dataDir: process.env.DISPATCH_DATA_DIR }),
    );
    const reload = spawnSync("systemctl", ["--user", "daemon-reload"], { encoding: "utf8" });
    if (reload.status !== 0) {
      return {
        ok: false,
        action,
        detail: "installed unit but systemctl --user daemon-reload failed",
        unitPath,
        stdout: reload.stdout ?? "",
        stderr: reload.stderr ?? "",
      };
    }
    const enable = runSystemctl(["enable"]);
    if (!enable.ok) return { ...enable, action, unitPath, detail: `installed unit but enable failed: ${enable.detail}` };
    if (opts.startAfterInstall) {
      const started = runSystemctl(["restart"]);
      return {
        ...started,
        action,
        unitPath,
        detail: started.ok ? `installed, enabled, and started ${SYSTEMD_SERVICE_NAME}` : `installed and enabled, but start failed`,
      };
    }
    return { ok: true, action, unitPath, detail: `installed and enabled ${SYSTEMD_SERVICE_NAME}` };
  }

  if (action === "uninstall") {
    const stop = runSystemctl(["disable", "--now"]);
    rmSync(unitPath, { force: true });
    const reload = spawnSync("systemctl", ["--user", "daemon-reload"], { encoding: "utf8" });
    spawnSync("systemctl", ["--user", "reset-failed", SYSTEMD_SERVICE_NAME], { encoding: "utf8" });
    return {
      ok: stop.ok || !existsSync(unitPath),
      action,
      unitPath,
      detail: stop.ok ? `disabled and removed ${SYSTEMD_SERVICE_NAME}` : "removed unit file; service was not enabled or systemctl --user failed",
      stdout: `${stop.stdout ?? ""}${reload.stdout ?? ""}`,
      stderr: `${stop.stderr ?? ""}${reload.stderr ?? ""}`,
    };
  }

  return runSystemctl([action]);
}
